### ISSUE TITLE
Validación: Resumen del consumo de recursos y potencia de la FPGA.

### ISSUE THREAD

**Issue by AnthonyAS15** [AnthonyAS15/AlgoritmodeBooth-MultiplicadorconSigno#11]
## Resumen del consumo de recursos y potencia de la FPGA
- Reportar el consumo de recursos en la FPGA y el consumo de potencia del diseño realizado. Todo esto a partir de la herramienta Vivado. 
 ## Objetivos 
### Objetivo General:
- Usar la aplicación Vivado para observar el consumo de recursos de la FPGA según el circuito realizado. 
### Objetivos Específicos:
- Analizar el consumo de recursos de la FPGA (LUTs, FFs, etc.).
- Observar el consumo de potencia según la aplicación.
## Entregables
1. Realizar el reporte del consumo de recursos en la FPGA y el consumo de potencia del circuito. 
## Fecha de entrega
- Hacer los reportes antes del Jueves 16 de noviembre del 2022
## Colaboradores 
- [Anthony Artavia](https://github.com/AnthonyAS15) 
- [Diego Huertas](https://github.com/ElRiquitix) 
- [Justin Segura](https://github.com/Justinsegurar)

**Comment by Justinsegurar** [comment]
## Consumo de recursos, potencia del circuito.
- Reportar el consumo de recursos en la FPGA, el consumo de potencia y las velocidades máximas de reloj posibles en el diseño. Todo esto a partir de la herramienta Vivado.
## Pruebas realizadas 
### Consumo de recursos y potencias del circuito.


![Image](https://user-images.githubusercontent.com/111217127/202400930-813a9777-8e1f-4be6-81d9-45217eb05cfb.jpg)


## Fecha del entregable 
- Jueves 17 de noviembre

## Fecha de realización 

- Miércoles 16 de noviembre
