### ISSUE TITLE
Validación: Reporte de velocidades máximas de reloj posibles en el diseño.

### ISSUE THREAD

**Issue by AnthonyAS15** [AnthonyAS15/AlgoritmodeBooth-MultiplicadorconSigno#12]
## Reportar las velocidades de reloj del circuito en el diseño
- Reportar las velocidades máximas de reloj posibles en el diseño. Todo esto a partir de la herramienta Vivado. 
 ## Objetivos 
### Objetivo General:
- Usar la aplicación Vivado para observar el consumo de recursos de la FPGA según el circuito realizado. 
### Objetivos Específicos:
- Analizar el consumo de recursos de la FPGA (LUTs, FFs, etc.).
- Reportar las velocidades máximas de reloj posibles en el diseño.
## Entregables
1. Realizar el reporte de las velocidades reloj del circuito en el diseño del proyecto. 
## Fecha de entrega
- Hacer los reportes antes del Jueves 16 de noviembre del 2022
## Colaboradores 
- [Anthony Artavia](https://github.com/AnthonyAS15) 
- [Diego Huertas](https://github.com/ElRiquitix) 
- [Justin Segura](https://github.com/Justinsegurar)

**Comment by Justinsegurar** [comment]
## Consumo de recursos, potencia y velocidades de reloj del circuito.
- Reportar el consumo de recursos en la FPGA, el consumo de potencia y las velocidades máximas de reloj posibles en el diseño. Todo esto a partir de la herramienta Vivado.
## Pruebas realizadas 
### Velocidades del reloj del circuito. 



![Image](https://user-images.githubusercontent.com/111217127/202389557-665d987d-8ea6-4e25-a6ad-9e7ce6dffcd3.jpg)

## Fecha del entregable 
- Jueves 17 de noviembre

## Fecha de realización 

- Miércoles 16 de noviembre
