### ISSUE TITLE
Documentación: Análisis de los principales problemas hallados durante el trabajo y de las soluciones aplicadas.

### ISSUE THREAD

**Issue by AnthonyAS15** [AnthonyAS15/AlgoritmodeBooth-MultiplicadorconSigno#13]
## Analizar los principales problemas hallados durante el trabajo y las soluciones aplicadas 
- Analizar los principales problemas vistos durante la realización del proyecto y plantear las debidas soluciones a la hora de implementarlos. 
 ## Objetivos 
### Objetivo General:
- Inspeccionar los problemas y plantear las soluciones del proyecto a realizar. 
### Objetivos Específicos:
- Analizar los problemas encontrados durante la realización del proyecto. 
- Reportar los principales problemas y reportar las debidas soluciones del mismo. 
## Entregables
1. Encontrar los principales problemas y presentarle la solución de este. 
## Fecha de entrega
- Hacer los reportes antes del Jueves 16 de noviembre del 2022
## Colaboradores 
- [Anthony Artavia](https://github.com/AnthonyAS15) 
- [Diego Huertas](https://github.com/ElRiquitix) 
- [Justin Segura](https://github.com/Justinsegurar)

**Comment by ElRiquitix** [comment]
## Principales problemas hallados durante el trabajo


Dentro de las dificultades al realizar el subsistema 2 fue lograr elaborar la estructura que proporcionaba el profesor y manipular el código que él nos había pasado. Lo que llevo consigo distintas revisiones para lograr entenderlo, sin embargo, la solución vino cuando tuvimos una reunión con el profesor donde pudimos revisarlo junto con él, y de esta manera pudimos entenderlo.



De la misma manera, una de las dificultades al realizar las simulaciones, fue que no se estaba representando el resultado esperado en el display de 7segmentos de la Nexys debido a un problema en el código. Por este motivo, se llevó a cabo una larga depuración, donde se logró encontrar y corregirlo, de esta manera pudimos lograr representar el resultado de la conversión de manera correcta.


## Fecha del entregable 
- Jueves 17 de noviembre

**Comment by Justinsegurar** [comment]
## Principales problemas hallados durante el trabajo
Uno de los problemas que tuvimos es que estábamos es que estábamos tomando las multiplicaciones como si fueran operaciones combinacionales, sin embargo, en algunos casos se debían de tomar las multiplicaciones como si fueran secuenciales, por lo tanto, tuvimos algunas complicaciones a la hora de hacerle el cambio con respecto al subsistema de multiplicación. No obstante, se realizaron los cambios correspondientes y pudimos arreglar dicho problema. 

## Fecha del entregable 
- Jueves 17 de noviembre
