### ISSUE TITLE
Diseño: Diagrama de estado de la FSM.

### ISSUE THREAD

**Issue by AnthonyAS15** [AnthonyAS15/AlgoritmodeBooth-MultiplicadorconSigno#2]
## Diagrama de estado de la FSM
- Se debe realizar el diagrama de estado de la máquina de estados finitos que se va a usar en el proyecto.
 ## Objetivos 
### Objetivo General:
- Hacer el diagrama de estado.
### Objetivos Específicos:
- Crear el diagrama de estado de manera que se facilite el código.
- Consultar con el profesor si el diagrama es el más adecuado.

## Entregables: 
1. Realizar un diagrama FSM que exprese el funcionamiento del circuito. 
## Fecha de entrega:
-  Jueves 27 de octubre del 2022.

## Colaboradores 
- [Anthony Artavia](https://github.com/AnthonyAS15) 
- [Diego Huertas](https://github.com/ElRiquitix) 
- [Justin Segura](https://github.com/Justinsegurar)

**Comment by ElRiquitix** [comment]
## Subsistema de cálculo de multiplicación

Diagrama inicial hecho a mano que expresa el funcionamiento del subsistema

![Image](https://user-images.githubusercontent.com/110042626/198812898-d4777179-6f14-489e-bc15-6e050e6313bf.jpg)

## Fecha del entregable:
-  Jueves 27 de octubre del 2022.

## Fecha de entrega:
-  Viernes 28 de octubre del 2022.

**Comment by AnthonyAS15** [comment]
## Subsistema de cálculo de multiplicación
 Diagrama corregido y elaborado con software

![Diagrama de Estados](https://user-images.githubusercontent.com/73151507/201811087-cbd59364-3eaf-48af-992a-df780de26ffa.png)

## Fecha del entregable:
-  Jueves 27 de octubre del 2022.

## Fecha de entrega:
-  Viernes 28 de octubre del 2022.

**Comment by ElRiquitix** [comment]
## Subsistema conversión de binario a representación BCD
 Diagrama elaborado con software



![Image](https://user-images.githubusercontent.com/110042626/202409813-77992885-9d22-47b1-b264-b1c10f91b050.png)



## Fecha del entregable:
-  Jueves 27 de octubre del 2022.

## Fecha de entrega:
-  Lunes 31 de octubre del 2022.
