### ISSUE TITLE
Diseño: Diagramas de bloques de los subsistemas.

### ISSUE THREAD

**Issue by AnthonyAS15** [AnthonyAS15/AlgoritmodeBooth-MultiplicadorconSigno#3]
## Diagrama de estado de la FSM
- Se deben crear los diagramas de bloques de cada uno de los subsistemas para resolver el problema planteado en el proyecto.
 ## Objetivos 
### Objetivo General:
- Hacer los diagramas de estados.
### Objetivos Específicos:
- Crear el diagrama de bloques del subsistema de lectura.
- Crear el diagrama de bloques del subsistema de cálculo de multiplicación.
- Crear el diagrama de bloques del subsistema conversión de binario a representación BCD.
- Crear el diagrama de bloques del subsistema de despliegue en display de 7 segmentos.

## Entregables
1. Diagrama de bloques que exprese el "Subsistema de lectura de datos"
2. Diagrama de bloques que exprese el "Subsistema de cálculo de multiplicación"
3. Diagrama de bloques que exprese el "Subsistema de conversión de binario a representación BCD" 
4. Diagrama de bloques que exprese el "Subsistema de despliegue en display de 7 segmentos"
## Fecha de entrega 
- Jueves 27 de octubre del 2022.
## Colaboradores 
- [Anthony Artavia](https://github.com/AnthonyAS15) 
- [Diego Huertas](https://github.com/ElRiquitix) 
- [Justin Segura](https://github.com/Justinsegurar)

**Comment by Justinsegurar** [comment]
## Diagrama de bloques que exprese el "Subsistema de lectura de datos"

- Cada bit adquirido por por el sistema despliega en un LED próximo
al switch para indicar como fue leído.


![Image](https://user-images.githubusercontent.com/111217127/198816232-9513c6d3-9dec-4847-9999-13ab040475af.jpeg)

- Dicho subsistema, tiene como entradas los switches A y B, dos botones(Push Botton y reset), y por salida tiene la operación aritmética de dicho algoritmo. 


### Diagrama de bloques que exprese el "SynC" implementados en el "Subsistema de lectura de datos"



![Image](https://user-images.githubusercontent.com/111217127/201437074-1b5eb5a4-506b-422c-9ccb-4aa3623f2c2a.jpg)



## Fecha del entregable
- Jueves 27 de Octubre del 2022
## Fecha del trabajo realizado
- Viernes 28 de Octubre del 2022
## Comentario
- Se entregó días después, debido, a que se le tuvieron que hacer ciertas modificaciones al diagrama.

**Comment by ElRiquitix** [comment]
## Diagrama de bloques que exprese el "Subsistema de cálculo de multiplicación"

- El cálculo de multiplicación con signo se realizará de manera iterativa por medio del Algoritmo de
Booth.





![Image](https://user-images.githubusercontent.com/110042626/202101515-57748ebb-dbca-45c6-840a-051580af7cb4.png)



## Fecha del entregable
- Jueves 27 de Octubre del 2022
## Fecha del trabajo realizado
- Viernes 28 de Octubre del 2022
## Comentario
- Se entregó días después, debido, a que se le tuvieron que hacer ciertas modificaciones al diagrama.

**Comment by Justinsegurar** [comment]
### Diagrama de bloques que exprese el "SynC" implementados en el "Subsistema de lectura de datos"



![Image](https://user-images.githubusercontent.com/111217127/201437074-1b5eb5a4-506b-422c-9ccb-4aa3623f2c2a.jpg)



## Fecha del entregable
- Jueves 27 de Octubre del 2022
## Fecha del trabajo realizado
- Viernes 28 de Octubre del 2022

**Comment by Justinsegurar** [comment]
## Diagrama de bloques que exprese el "Subsistema conversión de binario a representación BCD"

- El cálculo de la conversión de binario a BCD




![Image](https://user-images.githubusercontent.com/110042626/202101682-323ce585-5b7a-41fb-9db4-4277fdf6a7a5.png)



## Fecha del entregable
- Jueves 27 de Octubre del 2022
## Fecha del trabajo realizado
- Viernes 28 de Octubre del 2022
## Comentario
- Se entregó días después, debido, a que se le tuvieron que hacer ciertas modificaciones al diagrama.

**Comment by ElRiquitix** [comment]
### Diagrama de bloques que exprese el "Subsistema de despliegue en display de 7 segmentos"



![Image](https://user-images.githubusercontent.com/111217127/201437213-a34185db-e395-4c00-8fea-3720e0567b5b.jpg)

- Dicho Subsistema, tiene como entradas el Subsistema conversión de binario a representación BCD  y por salida tiene el display de 7 segmentos que muestra el resultado de la operación realizada. 


## Fecha del entregable
- Jueves 27 de Octubre del 2022
## Fecha del trabajo realizado
- Viernes 28 de Octubre del 2022
## Comentario
- Se entregó días después, debido, a que se le tuvieron que hacer ciertas modificaciones al diagrama.
